/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WcHcAppDrawer {
        "opened": boolean;
    }
}
export interface WcHcAppDrawerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWcHcAppDrawerElement;
}
declare global {
    interface HTMLWcHcAppDrawerElementEventMap {
        "openedChanged": boolean;
    }
    interface HTMLWcHcAppDrawerElement extends Components.WcHcAppDrawer, HTMLStencilElement {
        addEventListener<K extends keyof HTMLWcHcAppDrawerElementEventMap>(type: K, listener: (this: HTMLWcHcAppDrawerElement, ev: WcHcAppDrawerCustomEvent<HTMLWcHcAppDrawerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLWcHcAppDrawerElementEventMap>(type: K, listener: (this: HTMLWcHcAppDrawerElement, ev: WcHcAppDrawerCustomEvent<HTMLWcHcAppDrawerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLWcHcAppDrawerElement: {
        prototype: HTMLWcHcAppDrawerElement;
        new (): HTMLWcHcAppDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "wc-hc-app-drawer": HTMLWcHcAppDrawerElement;
    }
}
declare namespace LocalJSX {
    interface WcHcAppDrawer {
        "onOpenedChanged"?: (event: WcHcAppDrawerCustomEvent<boolean>) => void;
        "opened"?: boolean;
    }
    interface IntrinsicElements {
        "wc-hc-app-drawer": WcHcAppDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wc-hc-app-drawer": LocalJSX.WcHcAppDrawer & JSXBase.HTMLAttributes<HTMLWcHcAppDrawerElement>;
        }
    }
}
